//SETTINGS MENU, may not be entirely Yellow-specific

ds_map_add(global.text_data_en, "settings_page1", "< PAGE 1 >")
ds_map_add(global.text_data_en, "settings_page2", "< PAGE 2 >")
ds_map_add(global.text_data_en, "settings_page2", "< PAGE 3 >")

//YELLOW Items
ds_map_add(global.text_data_en, "item_name_65", "Patch")
ds_map_add(global.text_data_en, "item_name_66", "Rubber Ammo")
ds_map_add(global.text_data_en, "item_name_67", "Feather")
ds_map_add(global.text_data_en, "item_name_68", "Pebble Ammo")
ds_map_add(global.text_data_en, "item_name_69", "Candy Corn")
ds_map_add(global.text_data_en, "item_name_70", "Corn Dog")
ds_map_add(global.text_data_en, "item_name_71", "Lemonade")
ds_map_add(global.text_data_en, "item_name_72", "Sponge Cake")
ds_map_add(global.text_data_en, "item_name_73", "Golden Pear")
ds_map_add(global.text_data_en, "item_name_74", "Toy Gun")
ds_map_add(global.text_data_en, "item_name_75", "Wild Revolver")
ds_map_add(global.text_data_en, "item_name_76", "Worn Hat")
ds_map_add(global.text_data_en, "item_name_77", "Nice Hat")
ds_map_add(global.text_data_en, "item_name_78", "Ice Pellets")
ds_map_add(global.text_data_en, "item_name_79", "Coffee Bean Ammo")
ds_map_add(global.text_data_en, "item_name_80", "Flint")
ds_map_add(global.text_data_en, "item_name_81", "Glass Ammo")
ds_map_add(global.text_data_en, "item_name_82", "Silver Ammo")
ds_map_add(global.text_data_en, "item_name_83", "Nails")
ds_map_add(global.text_data_en, "item_name_84", "Friendliness Pellets")
ds_map_add(global.text_data_en, "item_name_85", "Honeydew Pin")
ds_map_add(global.text_data_en, "item_name_86", "Band Merch Pin")
ds_map_add(global.text_data_en, "item_name_87", "Silver Scarf")
ds_map_add(global.text_data_en, "item_name_88", "Steel Buckle")
ds_map_add(global.text_data_en, "item_name_89", "Safety Jacket")
ds_map_add(global.text_data_en, "item_name_90", "Fancy Holster")
ds_map_add(global.text_data_en, "item_name_91", "Safety Goggles")
ds_map_add(global.text_data_en, "item_name_92", "Golden Bandana")
ds_map_add(global.text_data_en, "item_name_93", "Delta Rune Patch")
ds_map_add(global.text_data_en, "item_name_94", "Honeydew Coffee")
ds_map_add(global.text_data_en, "item_name_95", "Adult Soda")
ds_map_add(global.text_data_en, "item_name_96", "Honeydew Pancake")
ds_map_add(global.text_data_en, "item_name_97", "G.B. Bear")
ds_map_add(global.text_data_en, "item_name_98", "Hot Pop")
ds_map_add(global.text_data_en, "item_name_99", "Lukewarm Pop")
ds_map_add(global.text_data_en, "item_name_100", "Cold Pop")
ds_map_add(global.text_data_en, "item_name_101", "Golden Coffee")
ds_map_add(global.text_data_en, "item_name_102", "Golden Cactus")
ds_map_add(global.text_data_en, "item_name_103", "Packing Peanuts")
ds_map_add(global.text_data_en, "item_name_104", "Trail Mix")
ds_map_add(global.text_data_en, "item_name_105", "Ice Tea")
ds_map_add(global.text_data_en, "item_name_106", "Green Tea")
ds_map_add(global.text_data_en, "item_name_107", "Sea Tea")
ds_map_add(global.text_data_en, "item_name_108", "Fruitcake")
ds_map_add(global.text_data_en, "item_name_109", "Icewater")
ds_map_add(global.text_data_en, "item_name_110", "Oasis Latte")
ds_map_add(global.text_data_en, "item_name_111", "Cinnamon Cookie")
ds_map_add(global.text_data_en, "item_name_112", "Root Beer")
ds_map_add(global.text_data_en, "item_name_113", "Feisty Slider")
ds_map_add(global.text_data_en, "item_name_114", "Gunpowder")
ds_map_add(global.text_data_en, "item_name_115", "Moss Salad")
ds_map_add(global.text_data_en, "item_name_116", "Grassy Fries")
ds_map_add(global.text_data_en, "item_name_117", "Flower Stew")
ds_map_add(global.text_data_en, "item_name_118", "Gravity Granola")
ds_map_add(global.text_data_en, "item_name_119", "Dihydrogen Monoxide")
ds_map_add(global.text_data_en, "item_name_120", "Beef Jerky")
ds_map_add(global.text_data_en, "item_name_121", "Cake")
ds_map_add(global.text_data_en, "item_name_122", "Floral Cupcake")
ds_map_add(global.text_data_en, "item_name_123", "Monster Candy+")
ds_map_add(global.text_data_en, "item_name_124", "Cinnamon-Butterscotch Strudel")
ds_map_add(global.text_data_en, "item_name_125", "Hot Dog")
ds_map_add(global.text_data_en, "item_name_126", "Corn Chowder")
ds_map_add(global.text_data_en, "item_name_127", "Missing Poster")
ds_map_add(global.text_data_en, "item_name_128", "Lukewarm Coffee")
ds_map_add(global.text_data_en, "item_name_129", "Soggy Mitten")
ds_map_add(global.text_data_en, "item_name_130", "Matches")
ds_map_add(global.text_data_en, "item_name_131", "Snowdin Map")
ds_map_add(global.text_data_en, "item_name_132", "Videotape")
ds_map_add(global.text_data_en, "item_name_133", "H. Acid")
ds_map_add(global.text_data_en, "item_name_134", "Cinnamon-Butterscotch Strudel")
ds_map_add(global.text_data_en, "item_name_135", "Hot Dog")
ds_map_add(global.text_data_en, "item_name_136", "Corn Chowder")
ds_map_add(global.text_data_en, "item_name_137", "Missing Poster")
ds_map_add(global.text_data_en, "item_name_138", "Lukewarm Coffee")
ds_map_add(global.text_data_en, "item_name_139", "Soggy Mitten")

ds_map_add(global.text_data_en, "item_nameb_65", "Patch")
ds_map_add(global.text_data_en, "item_nameb_66", "RubbrAmmo")
ds_map_add(global.text_data_en, "item_nameb_67", "Feather")
ds_map_add(global.text_data_en, "item_nameb_68", "PebblAmmo")
ds_map_add(global.text_data_en, "item_nameb_69", "CandyCorn")
ds_map_add(global.text_data_en, "item_nameb_70", "Corn Dog")
ds_map_add(global.text_data_en, "item_nameb_71", "Lemonade")
ds_map_add(global.text_data_en, "item_nameb_72", "SpongCake")
ds_map_add(global.text_data_en, "item_nameb_73", "Gold Pear")
ds_map_add(global.text_data_en, "item_nameb_74", "Toy Gun")
ds_map_add(global.text_data_en, "item_nameb_75", "WildRevlr")
ds_map_add(global.text_data_en, "item_nameb_76", "Worn Hat")
ds_map_add(global.text_data_en, "item_nameb_77", "Nice Hat")
ds_map_add(global.text_data_en, "item_nameb_78", "IcePelets")
ds_map_add(global.text_data_en, "item_nameb_79", "CBeanAmmo")
ds_map_add(global.text_data_en, "item_nameb_80", "Flint")
ds_map_add(global.text_data_en, "item_nameb_81", "GlassAmmo")
ds_map_add(global.text_data_en, "item_nameb_82", "SilvrAmmo")
ds_map_add(global.text_data_en, "item_nameb_83", "Nails")
ds_map_add(global.text_data_en, "item_nameb_84", "FrendPelt")
ds_map_add(global.text_data_en, "item_nameb_85", "HD Pin")
ds_map_add(global.text_data_en, "item_nameb_86", "Band Pin")
ds_map_add(global.text_data_en, "item_nameb_87", "Sil.Scarf")
ds_map_add(global.text_data_en, "item_nameb_88", "SteelBuck")
ds_map_add(global.text_data_en, "item_nameb_89", "SafeJackt")
ds_map_add(global.text_data_en, "item_nameb_90", "FancyHols")
ds_map_add(global.text_data_en, "item_nameb_91", "SafeGogls")
ds_map_add(global.text_data_en, "item_nameb_92", "GoBandana")
ds_map_add(global.text_data_en, "item_nameb_93", "DeltaPtch")
ds_map_add(global.text_data_en, "item_nameb_94", "HD Coffee")
ds_map_add(global.text_data_en, "item_nameb_95", "AdultSoda")
ds_map_add(global.text_data_en, "item_nameb_96", "HDPancake")
ds_map_add(global.text_data_en, "item_nameb_97", "G.B. Bear")
ds_map_add(global.text_data_en, "item_nameb_98", "Hot Pop")
ds_map_add(global.text_data_en, "item_nameb_99", "LukwrmPop")
ds_map_add(global.text_data_en, "item_nameb_100", "Cold Pop")
ds_map_add(global.text_data_en, "item_nameb_101", "GldCoffee")
ds_map_add(global.text_data_en, "item_nameb_102", "GldCactus")
ds_map_add(global.text_data_en, "item_nameb_103", "PackPnuts")
ds_map_add(global.text_data_en, "item_nameb_104", "Trail Mix")
ds_map_add(global.text_data_en, "item_nameb_105", "Ice Tea")
ds_map_add(global.text_data_en, "item_nameb_106", "Green Tea")
ds_map_add(global.text_data_en, "item_nameb_107", "Sea Tea")
ds_map_add(global.text_data_en, "item_nameb_108", "Fruitcake")
ds_map_add(global.text_data_en, "item_nameb_109", "Icewater")
ds_map_add(global.text_data_en, "item_nameb_110", "OasisLate")
ds_map_add(global.text_data_en, "item_nameb_111", "CinnaCoki")
ds_map_add(global.text_data_en, "item_nameb_112", "Root Beer")
ds_map_add(global.text_data_en, "item_nameb_113", "FstySlidr")
ds_map_add(global.text_data_en, "item_nameb_114", "Gunpowder")
ds_map_add(global.text_data_en, "item_nameb_115", "MossSalad")
ds_map_add(global.text_data_en, "item_nameb_116", "GrassFrys")
ds_map_add(global.text_data_en, "item_nameb_117", "FlowrStew")
ds_map_add(global.text_data_en, "item_nameb_118", "GravyGran")
ds_map_add(global.text_data_en, "item_nameb_119", "H2o")
ds_map_add(global.text_data_en, "item_nameb_120", "BeefJerky")
ds_map_add(global.text_data_en, "item_nameb_121", "Cake")
ds_map_add(global.text_data_en, "item_nameb_122", "FlrCupcke")
ds_map_add(global.text_data_en, "item_nameb_123", "MstrCndy+")
ds_map_add(global.text_data_en, "item_nameb_124", "ButtStrdl")
ds_map_add(global.text_data_en, "item_nameb_125", "Hot Dog")
ds_map_add(global.text_data_en, "item_nameb_126", "CrnChowdr")
ds_map_add(global.text_data_en, "item_nameb_127", "M. Poster")
ds_map_add(global.text_data_en, "item_nameb_128", "LwrmCofee")
ds_map_add(global.text_data_en, "item_nameb_129", "SoggyMitt")
ds_map_add(global.text_data_en, "item_nameb_130", "Matches")
ds_map_add(global.text_data_en, "item_nameb_131", "SnowMap")
ds_map_add(global.text_data_en, "item_nameb_132", "Videotape")
ds_map_add(global.text_data_en, "item_nameb_133", "H. Acid")
ds_map_add(global.text_data_en, "item_nameb_134", "CB Strudl")
ds_map_add(global.text_data_en, "item_nameb_135", "Hot Dog")
ds_map_add(global.text_data_en, "item_nameb_136", "CrnChowdr")
ds_map_add(global.text_data_en, "item_nameb_137", "M. Poster")
ds_map_add(global.text_data_en, "item_nameb_138", "WrmCoffee")
ds_map_add(global.text_data_en, "item_nameb_139", "SoggyMits")

ds_map_add(global.text_data_en, "item_names_65", "Patch")
ds_map_add(global.text_data_en, "item_names_66", "Rubber")
ds_map_add(global.text_data_en, "item_names_67", "Feather")
ds_map_add(global.text_data_en, "item_names_68", "Pebbles")
ds_map_add(global.text_data_en, "item_names_69", "CandyCorn")
ds_map_add(global.text_data_en, "item_names_70", "Corn Dog")
ds_map_add(global.text_data_en, "item_names_71", "Lemonade")
ds_map_add(global.text_data_en, "item_names_72", "S. Cake")
ds_map_add(global.text_data_en, "item_names_73", "Gold Pear")
ds_map_add(global.text_data_en, "item_names_74", "Toy Gun")
ds_map_add(global.text_data_en, "item_names_75", "Revolver")
ds_map_add(global.text_data_en, "item_names_76", "Worn Hat")
ds_map_add(global.text_data_en, "item_names_77", "Nice Hat")
ds_map_add(global.text_data_en, "item_names_78", "Ice Ammo")
ds_map_add(global.text_data_en, "item_names_79", "Bean Ammo")
ds_map_add(global.text_data_en, "item_names_80", "Flint")
ds_map_add(global.text_data_en, "item_names_81", "GlassAmmo")
ds_map_add(global.text_data_en, "item_names_82", "SilvrAmmo")
ds_map_add(global.text_data_en, "item_names_83", "Nails")
ds_map_add(global.text_data_en, "item_names_84", "F.Pellets")
ds_map_add(global.text_data_en, "item_names_85", "Honey Pin")
ds_map_add(global.text_data_en, "item_names_86", "Band Pin")
ds_map_add(global.text_data_en, "item_names_87", "Scarf")
ds_map_add(global.text_data_en, "item_names_88", "Buckle")
ds_map_add(global.text_data_en, "item_names_89", "S. Jacket")
ds_map_add(global.text_data_en, "item_names_90", "Holster")
ds_map_add(global.text_data_en, "item_names_91", "S.Goggles")
ds_map_add(global.text_data_en, "item_names_92", "G.Bandana")
ds_map_add(global.text_data_en, "item_names_93", "DeltaPtch")
ds_map_add(global.text_data_en, "item_names_94", "H. Coffee")
ds_map_add(global.text_data_en, "item_names_95", "AdultSoda")
ds_map_add(global.text_data_en, "item_names_96", "H.Pancake")
ds_map_add(global.text_data_en, "item_names_97", "G.B. Bear")
ds_map_add(global.text_data_en, "item_names_98", "Hot Pop")
ds_map_add(global.text_data_en, "item_names_99", "Lw. Pop")
ds_map_add(global.text_data_en, "item_names_100", "Cold Pop")
ds_map_add(global.text_data_en, "item_names_101", "GldCoffee")
ds_map_add(global.text_data_en, "item_names_102", "GldCactus")
ds_map_add(global.text_data_en, "item_names_103", "Peanuts")
ds_map_add(global.text_data_en, "item_names_104", "Trail Mix")
ds_map_add(global.text_data_en, "item_names_105", "Ice Tea")
ds_map_add(global.text_data_en, "item_names_106", "Green Tea")
ds_map_add(global.text_data_en, "item_names_107", "Sea Tea")
ds_map_add(global.text_data_en, "item_names_108", "Fruitcake")
ds_map_add(global.text_data_en, "item_names_109", "Icewater")
ds_map_add(global.text_data_en, "item_names_110", "O. Latte")
ds_map_add(global.text_data_en, "item_names_111", "Cookie")
ds_map_add(global.text_data_en, "item_names_112", "Root Beer")
ds_map_add(global.text_data_en, "item_names_113", "Slider")
ds_map_add(global.text_data_en, "item_names_114", "Gunpowder")
ds_map_add(global.text_data_en, "item_names_115", "MossSalad")
ds_map_add(global.text_data_en, "item_names_116", "GrassFrys")
ds_map_add(global.text_data_en, "item_names_117", "FlowrStew")
ds_map_add(global.text_data_en, "item_names_118", "G.Granola")
ds_map_add(global.text_data_en, "item_names_119", "Water")
ds_map_add(global.text_data_en, "item_names_120", "BeefJerky")
ds_map_add(global.text_data_en, "item_names_121", "Cake")
ds_map_add(global.text_data_en, "item_names_122", "F.Cupcake")
ds_map_add(global.text_data_en, "item_names_123", "M.Candy+")
ds_map_add(global.text_data_en, "item_names_124", "Strudel")
ds_map_add(global.text_data_en, "item_names_125", "Hot Dog")
ds_map_add(global.text_data_en, "item_names_126", "Chowder")
ds_map_add(global.text_data_en, "item_names_127", "Poster")
ds_map_add(global.text_data_en, "item_names_128", "Lw.Coffee")
ds_map_add(global.text_data_en, "item_names_129", "Mitten")
ds_map_add(global.text_data_en, "item_names_130", "Matches")
ds_map_add(global.text_data_en, "item_names_131", "Map")
ds_map_add(global.text_data_en, "item_names_132", "Videotape")
ds_map_add(global.text_data_en, "item_names_133", "H. Acid")
ds_map_add(global.text_data_en, "item_names_134", "Strudel")
ds_map_add(global.text_data_en, "item_names_135", "Hot Dog")
ds_map_add(global.text_data_en, "item_names_136", "Chowder")
ds_map_add(global.text_data_en, "item_names_137", "Poster")
ds_map_add(global.text_data_en, "item_names_138", "Lw.Coffee")
ds_map_add(global.text_data_en, "item_names_139", "Mitten")

ds_map_add(global.text_data_en, "item_desc_65_0", "* " + '"' + "Patch" + '"' + " - Acce DF 0&* (It's not strong but it's&  trustworthy.)/%")
ds_map_add(global.text_data_en, "item_desc_66_0", "* " + '"' + "Rubber Ammo" + '"' + " - Ammo AT 0&* (Small,^1 safe,^1 non-toxic &  rubber pellets.)/%")
ds_map_add(global.text_data_en, "item_desc_67_0", "* " + '"' + "Feather" + '"' + " - Armor DF 3&* (An old,^1 forgotten feather.^2& * It needs a good preening.)/%")
ds_map_add(global.text_data_en, "item_desc_68_0", "* " + '"' + "Pebbles" + '"' + " - Ammo AT 3&* (Like rocks, but smaller.)^2&* (Good makeshift ammo.)/%")
ds_map_add(global.text_data_en, "item_desc_69_0", "* " + '"' + "Candy Corn" + '"' + " - Heals 9 HP&* (Your teeth hurt just looking&  at it.)/%")
ds_map_add(global.text_data_en, "item_desc_70_0", "* " + '"' + "Corn Dog" + '"' + " - Heals 12 HP&* (A genuine Corn Dog with&  soft,^1 fluffy ears.)/")
ds_map_add(global.text_data_en, "item_desc_71_0", "* " + '"' + "Lemonade" + '"' + " - Heals 7 HP&* (Doesn't smell too appetizing.)/%")
ds_map_add(global.text_data_en, "item_desc_72_0", "* " + '"' + "Sponge Cake" + '"' + " - Heals 14 HP&* (A delicious sponge that doesn't&  scratch AND has 2x the&  absorption!)/")
ds_map_add(global.text_data_en, "item_desc_73_0", "* " + '"' + "Golden Pear" + '"' + "*  (Makes you invulnerable&* for a pear of hits.)/%")
ds_map_add(global.text_data_en, "item_desc_74_0", "* " + '"' + "Toy Gun" + '"' + " - Weapon AT 0&*  (A plastic gun bought from your favorite toy store.)^2&* (Even if it isn't the real deal,^1 it is& still capable of shooting real bullets.)/%")
ds_map_add(global.text_data_en, "item_desc_75_0", "* " + '"' + "Wild Revolver" + '"' + " - Weapon AT 12&*  (An antique revolver with a six-bullet chamber.)^2&* (It's hard to aim,^1 but it packs a punch.)/%")
ds_map_add(global.text_data_en, "item_desc_76_0", "* " + '"' + "Worn Hat" + '"' + " - Armor DF 0&* (Your old cowboy hat.)^2& * (Looks great with a beard.)/%")
ds_map_add(global.text_data_en, "item_desc_77_0", "* " + '"' + "Nice Hat" + '"' + " - Armor DF 0&* (A very fashionable cowboy hat.)^2& * (It's just your size!)/%")
ds_map_add(global.text_data_en, "item_desc_83_0", "* " + '"' + "Nails" + '"' + " - Ammo AT 12&* (Small, pointed pieces of&  steel.)/")
ds_map_add(global.text_data_en, "item_desc_83_0", "* (Could be quite effective if&  fired at a high velocity.)/%")
ds_map_add(global.text_data_en, "item_desc_127_0", "* (The grim reminder of your &  mission.)^2 &* (Justice is needed.)/%")

ds_map_add(global.text_data_en, "stat_menu_weapon2", "AMMO: \[1]")
ds_map_add(global.text_data_en, "stat_menu_armor2", "ACCE: \[1]")

ds_map_add(global.text_data_en, "item_use_65", "* (You are unable to sew the& Patch back onto your hat.)/%%")
ds_map_add(global.text_data_en, "item_use_66", "* (You load the rubber ammo into&  your weapon.)/%%")
ds_map_add(global.text_data_en, "item_use_67", "* (You are unable to sew the& Patch back onto your hat.)/%%")
ds_map_add(global.text_data_en, "item_use_68", "* (You load the pebbles into your&  gun.)/")
ds_map_add(global.text_data_en, "item_use_68a", "* (It feels a little heavier&  now.)/%%")
ds_map_add(global.text_data_en, "item_use_69", "* (You are unable to sew the& Patch back onto your hat.)/%%")
ds_map_add(global.text_data_en, "item_use_70", "* (You are unable to sew the& Patch back onto your hat.)/%%")
ds_map_add(global.text_data_en, "item_use_83", "* (You load the Nails&  into your gun.)/%%")
ds_map_add(global.text_data_en, "item_use_127", "* You presented the poster.^2 &* Froggit's eyes widened with&  familiarity./%%")

//SAVE Room Names
//Dark Ruins
ds_map_add(global.text_data_en, "roomname_darkruins_03", "Dark Ruins - Entrance");
ds_map_add(global.text_data_en, "roomname_darkruins_08", "Dark Ruins - Atrium");
ds_map_add(global.text_data_en, "roomname_darkruins_10", "Dark Ruins - Cliff");
ds_map_add(global.text_data_en, "roomname_darkruins_12", "Dark Ruins - Puzzle");
ds_map_add(global.text_data_en, "roomname_darkruins_16", "Dark Ruins - Hall");
//Tundra Yellow
ds_map_add(global.text_data_en, "roomname_snowdin_03_yellow", "Snowdin - Delta Rock");
ds_map_add(global.text_data_en, "roomname_snowdin_08_yellow", "Snowdin - Ruined Shack");
ds_map_add(global.text_data_en, "roomname_snowdin_12_yellow", "Snowdin - Pathway");
ds_map_add(global.text_data_en, "roomname_snowdin_14_yellow", "Snowdin - Resort");
ds_map_add(global.text_data_en, "roomname_snowdin_20_yellow", "Snowdin - Benches");
//Dunes
ds_map_add(global.text_data_en, "roomname_dunes_02", "Dunes - Cave");
ds_map_add(global.text_data_en, "roomname_dunes_08", "Dunes - Tree");
ds_map_add(global.text_data_en, "roomname_dunes_14", "Dunes - Mines Elevaor");
ds_map_add(global.text_data_en, "roomname_dunes_20", "Dunes - Minecart");
ds_map_add(global.text_data_en, "roomname_dunes_25", "Dunes - Mountaintop");
ds_map_add(global.text_data_en, "roomname_dunes_28", "Dunes - Playground");
ds_map_add(global.text_data_en, "roomname_dunes_34", "Dunes - Well");
ds_map_add(global.text_data_en, "roomname_dunes_37", "Dunes - Wild East");
ds_map_add(global.text_data_en, "roomname_dunes_39", "Dunes - Outskirts");
ds_map_add(global.text_data_en, "roomname_dunes_41", "Dunes - Sunnyside");
//Cerboba's Manjin
ds_map_add(global.text_data_en, "roomname_mansion_entrance", "Estate");

//Savepoint Dialogue
//Dark Ruins
//DARKRUINS_8
//Talk to Flowey once
ds_map_add(global.text_data_en, "obj_flowey_save_darkruins8_1_1", "\E0* Howdy!/")
ds_map_add(global.text_data_en, "obj_flowey_save_darkruins8_1_2", "\E9* I see you're still in one piece!/")
ds_map_add(global.text_data_en, "obj_flowey_save_darkruins8_1_3", "\E8* You saw that weirdo&  right?")
ds_map_add(global.text_data_en, "obj_flowey_save_darkruins8_1_4", "\E9* If you want to get out&  of here you'll have to&  go through him./")
ds_map_add(global.text_data_en, "obj_flowey_save_darkruins8_1_5", "\E0* He shouldn't be a&  problem though./")
ds_map_add(global.text_data_en, "obj_flowey_save_darkruins8_1_6", "* And if he is,^1 that's why&  I'm here!/%%")
//Talk to Flowey again
ds_map_add(global.text_data_en, "obj_flowey_save_darkruins8_2_1", "\E0* Again?/")
ds_map_add(global.text_data_en, "obj_flowey_save_darkruins8_2_2", "\E9* Okay, you're double&  saved now!/%%")
//Talk to Flowey a third time
ds_map_add(global.text_data_en, "obj_flowey_save_darkruins8_3_1", "\E8* Again?^2 Really?/")
ds_map_add(global.text_data_en, "obj_flowey_save_darkruins8_3_2", "\E9* How many saves do you&  need?/%%")
//DARKRUINS_10
//Talk to Flowey once
ds_map_add(global.text_data_en, "obj_flowey_save_darkruins10_1_1", "\E0* Howdy!/")
ds_map_add(global.text_data_en, "obj_flowey_save_darkruins10_1_2", "* Golly,^1 this place sure&  is dead!")
ds_map_add(global.text_data_en, "obj_flowey_save_darkruins10_1_3", "\E0* All the monsters are&  all quiet and lurking./")
ds_map_add(global.text_data_en, "obj_flowey_save_darkruins10_1_4", "\E0* That's not like monsters&  at all!/")
ds_map_add(global.text_data_en, "obj_flowey_save_darkruins10_1_5", "\E0* Don't let this ruin&  your impression of&  the Underground!/")
ds_map_add(global.text_data_en, "obj_flowey_save_darkruins10_1_6", "\E0* We'll leave this&  dump behind soon&  enough!/%%")
//Talk to Flowey a second time
ds_map_add(global.text_data_en, "obj_flowey_save_darkruins10_2_1", "\E0* You're already saved,^1 &  let's get a move&  on!/%%")
//DARKRUINS_12
//Talk to Flowey once
ds_map_add(global.text_data_en, "obj_flowey_save_darkruins12_1_1", "\E0* Howdy!/")
ds_map_add(global.text_data_en, "obj_flowey_save_darkruins12_1_2", "\E0* You seem to be doing&  well!/")
//Flowey checks for a death tally... I should probably program a functional Monster able to kill the player.

//Talk to Flowey twice
ds_map_add(global.text_data_en, "obj_flowey_save_darkruins12_2_1", "\E0* Howdy!/")
ds_map_add(global.text_data_en, "obj_flowey_save_darkruins12_2_2", "\E0* You seem to be doing&  well!/%%")

//YELLOW Monster Names

ds_map_add(global.text_data_en, "monstername_101", "Flier")
ds_map_add(global.text_data_en, "monstername_102", "Penilla")
ds_map_add(global.text_data_en, "monstername_103", "Sweet Corn")
ds_map_add(global.text_data_en, "monstername_104", "Rorrim")
ds_map_add(global.text_data_en, "monstername_105", "Crispy Scroll")
ds_map_add(global.text_data_en, "monstername_106", "Decibat")
ds_map_add(global.text_data_en, "monstername_107", "Dalv")
ds_map_add(global.text_data_en, "monstername_108", "Micro Froggit")
ds_map_add(global.text_data_en, "monstername_109", "Frostermit")

//YELLOW Monster Encounter Texts
//Intro Text
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_1", "* Flier is giving fighting a try!")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_2", "* You are overwhelmed by&  depressing vibes.")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_3", "* Penilla draws near!")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_4", "* Penilla seems to be dreading#  this battle.")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_5", "* Sweet Corn hops up excitedly.")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_6", "* You can already feel the&  cavities.")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_7", "* Penilla encounters you.&* Sweet Corn comes out of nowhere&  acting excited.")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_8", "* Crispy Scroll is looking for&  someone to talk to.")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_9", "* A powerful lone warrior and his&  pencil companion encounter you!")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_10", "* It's a mirror match!")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_11", "* Decibat makes his presence&  known.")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_12", "* Penilla draws near!")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_13", "* Dalv musters his fighting&  spirit.")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_14", "* You notice Micro Froggit&  attacking you!")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_15", "* Insomnitot staggers forward.")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_16", "* You suddenly feel like taking a&  nap.")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_17", "* Know Cone comes to see if you&  are made of fire.&* You aren't.")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_18", "* Insomnitot appears!&* Know Cone wanders in, chasing a&  butterfly.")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_19", "* There is an igloo here.")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_20", "* Know Cone encounters you, and&  an igloo.")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_21", "* Trihecta wobbles forward!")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_22", "* Trihecta regroups, then bickers.")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_23", "* Martlet of the Royal Guard is&  waiting for your turn.")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_24", "* Martlet seems puzzled.")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_25", "* Dunebud popped out of the sand!")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_26", "* Double trouble!")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_27", "* Cactony comes to share his pain.")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_28", "* Sir Slither has a proposition!&  (real)")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_29", "* Bowll charges near you!")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_30", "* Cactony wandered in, Sir&  Slither closely following.")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_31", "* It's time to dance!")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_32", "* (Another roadblock.)")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_33", "* Violetta passively approaches&  from the flowerbed.")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_34", "* Pedla approaches from the&  flowerbed, offering you a&  flower.")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_35", "* Rosa approaches from the&  flowerbed, twisting a flower in&  her hand.")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_36", "* ...")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_37", "* The atmosphere chills with ire.")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_38", "* Showdown!")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_39", "* Duel!")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_40", "* Telly-Vis tunes in!")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_41", "* Jandroid strolls up, whistling&  a pitchy tune.")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_42", "* Goosic has come to share some&  sounds.")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_43", "* Sousborg is ready to put your&  culinary skills to the test!")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_44", "* The robotic duo, Jandroid and&  Goosic, are here!")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_45", "* Rinse, repeated.")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_46", "* Axis Model 014, ready to&  attack!")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_47", "* Axis Model 014, ready to&  defend.")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_48", "* Guardener ensnares you!")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_49", "* (No turning back.)")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_50", "* (Let justice be done.)")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_51", "* Ceroba is shaken by the&  memory.")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_52", "* The zenith of Monsterkind.")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_53", "* Penilla draws near!")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_54", "* Penilla draws near!")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_55", "* Penilla draws near!")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_56", "* Penilla draws near!")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_57", "* Penilla draws near!")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_58", "* Penilla draws near!")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_59", "* Penilla draws near!")
ds_map_add(global.text_data_en, "SCR_BATTLE_INTROTEXT_YELLOW_60", "* Penilla draws near!")

//Monster Default Text
ds_map_add(global.text_data_en, "SCR_BATTLE_DEFAULTTEXT_YELLOW_1", "* Everything has that new car&  smell with a faint whiff of&  bodyspray.")
ds_map_add(global.text_data_en, "SCR_BATTLE_DEFAULTTEXT_YELLOW_2", "* Flier uses hip slang like the&  kids.")
ds_map_add(global.text_data_en, "SCR_BATTLE_DEFAULTTEXT_YELLOW_3", "* Flier doesn't think the&  position of " + '"enemy" fits him.')
ds_map_add(global.text_data_en, "SCR_BATTLE_DEFAULTTEXT_YELLOW_4", "* Flier is caught up in old&  memories.")

//Low HP Text
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_1", "* Flier is reconsidering his life&  choices.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_2", "* Flier seems to have several&  regrets.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_3", "* Penilla looks like she might&  crack under the pressure.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_4", "* Penilla tries to bite the&  bullet.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_5", "* Sweet Corn's smile looks forced.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_6", "* Sweet Corn is trying to stay&  positive.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_7", "* Crispy Scroll is relying on his&  self-imposed plot armor.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_8", "* Crispy Scroll is trying to&  teleport away.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_9", "* Your reflection is skewed.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_10", "* Rorrim regrets approaching you.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_11", "* Insomnitot is hoping it'll feel&  better in the morning.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_12", "* Insomnitot is drifting in and&  out of consciousness.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_13", "* Know Cone is quite enraged.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_14", "* Know Cone stomps his feet in a&  huff.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_15", "* The igloo does not appear to be&  structurally sound anymore.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_16", "* The igloo is making distressed&  noises.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_17", "* Frostermit is looking a bit&  crabby with you.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_18", "* Frostermit retreats inside for a&  moment to address a possible&  cave in.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_19", "* Trihecta is teetering this way&  and that.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_20", "* Hec is blaming their&  situation on Tri.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_21", "* Ta is tearing up.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_22", "* They're scrambling frantically.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_23", "* Now they are truly split apart.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_24", "* They don't know what to do.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_25", "* Dunebud is dazed.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_26", "* Sand is spilling everywhere.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_27", "* Cactony is swaying back and&  forth.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_28", "* Cactony sheds a tear and a few&  needles.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_29", "* Sir Slither tries to keep&  whatever's in his pot from&  spilling.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_30", "* Sir Slither can't slither away&  from this.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_31", "* A few new ravines have surfaced.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_32", "* Bowll may break into tears soon.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_33", "* Violetta tries not to cry.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_34", "* Pedla tries to stay positive.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_35", "* Rosa tries to stay strong.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_36", "* Petals fall around your feet.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_37", "* Telly is frantically flipping&  channels.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_38", "* Vis spits out a broken video&  cassette.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_39", "* Jandroid doesn't seem to know&  what they're doing anymore")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_40", "* You hear metallic and&  electrical noises as Jandroid&  twitches.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_41", "* Goosic struggles to keep&  dancing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_42", "* Goosic's music bends in and out&  of tune")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_43", "* Sousborg pours onion powder on&  his wounds.")
ds_map_add(global.text_data_en, "SCR_BATTLE_LOWHPTEXT_YELLOW_44", "* Sousborg is leaking oil.&  Vegetable oil.")

//Sparable Text
ds_map_add(global.text_data_en, "SCR_BATTLE_MERCYTEXT_YELLOW_1", "* Flier is ready to return to his&  regular life.")
ds_map_add(global.text_data_en, "SCR_BATTLE_MERCYTEXT_YELLOW_2", "* Penilla is packing up her art&  supplies for the day.")
ds_map_add(global.text_data_en, "SCR_BATTLE_MERCYTEXT_YELLOW_3", "* Sweet Corn is smiling&  contentedly.")
ds_map_add(global.text_data_en, "SCR_BATTLE_MERCYTEXT_YELLOW_4", "* Crispy Mode 2k!!")
ds_map_add(global.text_data_en, "SCR_BATTLE_MERCYTEXT_YELLOW_5", "* Rorrim is looking for his next&  big project.")
ds_map_add(global.text_data_en, "SCR_BATTLE_MERCYTEXT_YELLOW_6", "* Decibat is ready to return to&  sleep.")
ds_map_add(global.text_data_en, "SCR_BATTLE_MERCYTEXT_YELLOW_7", "* Dalv has lost all hope.")
ds_map_add(global.text_data_en, "SCR_BATTLE_MERCYTEXT_YELLOW_8", "* Dalv looks unsure of what to do.")
ds_map_add(global.text_data_en, "SCR_BATTLE_MERCYTEXT_YELLOW_9", "* Micro Froggit is waving goodbye.")
ds_map_add(global.text_data_en, "SCR_BATTLE_MERCYTEXT_YELLOW_10", "* Insomnitot is smiling at its&  dream.")
ds_map_add(global.text_data_en, "SCR_BATTLE_MERCYTEXT_YELLOW_11", "* Know Cone has been enlightened.")
ds_map_add(global.text_data_en, "SCR_BATTLE_MERCYTEXT_YELLOW_12", "* Frostermit is ready to scuttle&  on its way.")
ds_map_add(global.text_data_en, "SCR_BATTLE_MERCYTEXT_YELLOW_13", "* Dunebud is giggling.")
ds_map_add(global.text_data_en, "SCR_BATTLE_MERCYTEXT_YELLOW_14", "* Sir Slither can't convince&  you.")
ds_map_add(global.text_data_en, "SCR_BATTLE_MERCYTEXT_YELLOW_15", "* Cactony feels love for the&  first time.")
ds_map_add(global.text_data_en, "SCR_BATTLE_MERCYTEXT_YELLOW_16", "* Bowll is ready to discover his&  true self.")
ds_map_add(global.text_data_en, "SCR_BATTLE_MERCYTEXT_YELLOW_17", "* Violetta blushes.")
ds_map_add(global.text_data_en, "SCR_BATTLE_MERCYTEXT_YELLOW_18", "* Pedla lets out a warm smile.")
ds_map_add(global.text_data_en, "SCR_BATTLE_MERCYTEXT_YELLOW_19", "* Rosa gives you a thumbs up.")
ds_map_add(global.text_data_en, "SCR_BATTLE_MERCYTEXT_YELLOW_20", "* Starlo's left hand is&  shaking.")
ds_map_add(global.text_data_en, "SCR_BATTLE_MERCYTEXT_YELLOW_21", "* Telly-Vis hopes you enjoyed the&  program.")
ds_map_add(global.text_data_en, "SCR_BATTLE_MERCYTEXT_YELLOW_22", "* Jandroid finds you too&  hygienic.")
ds_map_add(global.text_data_en, "SCR_BATTLE_MERCYTEXT_YELLOW_23", "* Goosic is lost in the music.")
ds_map_add(global.text_data_en, "SCR_BATTLE_MERCYTEXT_YELLOW_24", "* Sousborg bows to your culinary&  mastery!")
ds_map_add(global.text_data_en, "SCR_BATTLE_MERCYTEXT_YELLOW_25", "* Axis has cooled off.")
ds_map_add(global.text_data_en, "SCR_BATTLE_MERCYTEXT_YELLOW_26", "* Guardener cools down as steam&  seeps from her arms.")
ds_map_add(global.text_data_en, "SCR_BATTLE_MERCYTEXT_YELLOW_27", "* Crispy Mode 2k!!")
ds_map_add(global.text_data_en, "SCR_BATTLE_MERCYTEXT_YELLOW_28", "* Crispy Mode 2k!!")

//Monster Status Text

//Idle Monster Chatter
ds_map_add(global.text_data_en, "SCR_BATTLE_IDLE_SPEECH_YELLOW_0", "I'm looking to&buy a boat!^2 Know&anyone selling?")
ds_map_add(global.text_data_en, "SCR_BATTLE_IDLE_SPEECH_YELLOW_1", "You know&anyone&selling&a boat?")
ds_map_add(global.text_data_en, "SCR_BATTLE_IDLE_SPEECH_YELLOW_2", "Yeah, I&might be&working&out ;)")
ds_map_add(global.text_data_en, "SCR_BATTLE_IDLE_SPEECH_YELLOW_3", "That new&rock&band is&great!")

//Act Monster Chatter
ds_map_add(global.text_data_en, "SCR_BATTLE_ACT_SPEECH_YELLOW_1", "I... This&isn't&really me...")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACT_SPEECH_YELLOW_2", "Something&needs to& change.")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACT_SPEECH_YELLOW_3", "Don't&come&near me!")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACT_SPEECH_YELLOW_4", "That's&right!^2 I&knew you&noticed!")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACT_SPEECH_YELLOW_5", "Yeah,^1 I&totally&agree.")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACT_SPEECH_YELLOW_6", "I don't&accept.")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACT_SPEECH_YELLOW_7", "Don't come near&me!")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACT_SPEECH_YELLOW_8", "Don't come near&me!")

//Check Text

ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_1", "* FLIER - ATK 4 DEF 2&* Flier feels nothing./^")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_2", "* FLIER - ATK 4 DEF 2&* Flier feels half-empty./^")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_3", "* FLIER - ATK 4 DEF 2&* Flier feels great!^2& * Thanks for CHECKing!/^")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_4", "* PENILLA - ATK 4 DEF 2&* A sketchy character.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_5", "* PENILLA - ATK 4 DEF 2&* Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_6", "* PENILLA - ATK 4 DEF 2&* Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_7", "* SWEET CORN - ATK 4 DEF 2&* Constantly on a sugar rush.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_8", "* SWEET CORN - ATK 4 DEF 2&* Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_9", "* SWEET CORN - ATK 4 DEF 2&* Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_10", "* CRISPY SCROLL - ATK 4 DEF 2&* Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_11", "* CRISPY SCROLL - ATK 4 DEF 2&* Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_12", "* CRISPY SCROLL - ATK 4 DEF 2&* Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_13", "* RORRIM - ATK 4 DEF 2& * Flier feels nothing./^")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_14", "* RORRIM - ATK 4 DEF 2& * Flier feels nothing./^")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_15", "* RORRIM - ATK 4 DEF 2& * Flier feels nothing./^")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_16", "* DECIBAT - ATK 4 DEF 2& * Flier feels nothing./^")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_17", "* DECIBAT - ATK 4 DEF 2& * Flier feels nothing./^")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_18", "* DECIBAT - ATK 4 DEF 2& * Flier feels nothing./^")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_19", "* DALV - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_20", "* DALV - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_21", "* DALV - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_22", "* MICRO FROGGIT - ATK 1 DEF 0& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_23", "* MICRO FROGGIT - ATK 1 DEF 0& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_24", "* MICRO FROGGIT - ATK 1 DEF 0& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_25", "* INSOMNITOT - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_26", "* INSOMNITOT - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_27", "* INSOMNITOT - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_28", "* KNOW CONE - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_29", "* KNOW CONE - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_30", "* KNOW CONE - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_31", "* FROSTERMIT - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_32", "* FROSTERMIT - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_33", "* FROSTERMIT - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_34", "* TRIHECTA - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_35", "* TRIHECTA - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_36", "* TRIHECTA - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_37", "* TRI - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_38", "* TRI - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_39", "* TRI - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_40", "* HEC - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_41", "* HEC - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_42", "* HEC - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_43", "* TA - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_44", "* TA - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_45", "* TA - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_46", "* MARTLET - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_47", "* MARTLET - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_48", "* MARTLET - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_49", "* DUNEBUD - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_20", "* DUNEBUD - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_21", "* DUNEBUD - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_22", "* CACTONY - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_23", "* CACTONY - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_24", "* CACTONY - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_25", "* SLITHER - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_26", "* SLITHER - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_27", "* SLITHER - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_28", "* BOWLL - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_29", "* BOWLL - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_20", "* BOWLL - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_21", "* EL BAILADOR - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_22", "* EL BAILADOR - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_23", "* EL BAILADOR - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_24", "* VIOLETTA - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_25", "* VIOLETTA - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_26", "* VIOLETTA - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_27", "* PEDLA - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_28", "* PEDLA - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_29", "* PEDLA - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_20", "* ROSA - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_21", "* ROSA - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_22", "* ROSA - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_23", "* DUMMY - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_24", "* CEROBA - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_25", "* STARLO - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_26", "* STARLO - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_27", "* ED - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_28", "* ED - ATK 4 DEF 2& * Flier feels nothing.")
ds_map_add(global.text_data_en, "SCR_BATTLE_CHECKYELLOW_29", "* ED - ATK 4 DEF 2& * Flier feels nothing.")

//ACTs List

ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_1", "   * Check         * Comfort&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_2", "   * Check         * Compliment&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_3", "   * Check         * Lick&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_4", "   * Check         * Transform&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_5", "   * Check         * Adjust&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_6", "   * Check         * Comfort&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_7", "   * Check         * Compliment&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_8", "   * Check         * Lick&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_9", "   * Check         * Transform&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_10", "   * Check         * Adjust&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_11", "   * Check         * Talk&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_12", "   * Check         * Talk&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_13", "   * Check         * Compliment&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_14", "   * Check         * Sing&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_15", "   * Check         * Encourage&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_16", "   * Check         * Inspect&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_17", "   * Check         * Push&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_18", "   * Check         * Laugh&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_19", "   * Check         * Rush&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_20", "   * Check         * Apologize&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_21", "   * Check         * Pat&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_22", "   * Check         * Touch&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_23", "   * Check         * Challenge&   * Challenge    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_24", "   * Check         * Clean&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_25", "   * Check         * Twirl&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_26", "   * Check         * Stare&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_27", "   * Check         * Flatter&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_28", "   * Check         * Accept&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_29", "   * Check         * Flatter&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_30", "   * Check         * Apologize&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_31", "   * Check         * Pat&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_32", "   * Check         * Touch&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_33", "   * Check         * Challenge&   * Challenge    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_34", "   * Check         * Clean&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_35", "   * Check         * Twirl&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_36", "   * Check         * Stare&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_37", "   * Check         * Flatter&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_38", "   * Check         * Accept&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_39", "   * Check         * Flatter&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_40", "   * Check         * Talk&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_41", "   * Check         * Resist&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_42", "   * Check         * Struggle&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_43", "   * Check         * Surrender&   * Challenge    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_44", "   * Check         * Spin&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_45", "   * Check         * Steady&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_46", "   * Check         * Question&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_47", "   * Check         * Watch&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_48", "   * Check         * Vibe&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_49", "   * Check         * Crack&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_50", "   * Check         * Boil&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_51", "   * Check         * Refrigerate&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_52", "   * Check         * Brace&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_53", "   * Check         * Compliment&   * Challenge    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_54", "   * Check         * Plan B&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_55", "   * Check         * Compliment&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_56", "   * Check         * Frog&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_57", "   * Check         * Push&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_58", "   * Check         * Gather&   * Compliment    * Criticize")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSLIST_YELLOW_59", "   * Check         * Forget&   * Compliment    * Criticize")

//ACT Text

ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSTEXT_1", "* You inform Flier that his life&  isn't half over,^1 he has a whole&  half left to go!/^")
ds_map_add(global.text_data_en, "SCR_BATTLE_ACTSTEXT_2", "* You inform Flier that his life&  isn't half over,^1 he has a whole&  half left to go!/^")

//Misc Text, Typically Boss Monologues
ds_map_add(global.text_data_en, "SCR_BATTLETEXT_YELLOW_1", "%%%")

//Item Pickups
ds_map_add(global.text_data_en, "SCR_TEXT_YELLOW_30", "* (A little pile of conveniently&  bullet shaped pebbles.)/")
ds_map_add(global.text_data_en, "SCR_TEXT_YELLOW_31", "* (Take them?)& &         Yes         No      \C ")
ds_map_add(global.text_data_en, "SCR_TEXT_YELLOW_32", " ")
ds_map_add(global.text_data_en, "SCR_TEXT_YELLOW_33", "* (Obtained Pebbles!)/%%")
ds_map_add(global.text_data_en, "SCR_TEXT_YELLOW_34", "* (Not enough space.)/%%")
ds_map_add(global.text_data_en, "SCR_TEXT_YELLOW_35", "* (Pebbles are too dangerous.)/%%")

//YELLOW English Dialogues. Not sure how I'd go about separating these since they aren't simple numbers (I think)

//RUINS//

ds_map_add(global.text_data_en, "obj_encountertrigger1_1", "\E0* Ah!^2 Hello!/")
ds_map_add(global.text_data_en, "obj_encountertrigger1_2", "* Are you all right?/")
ds_map_add(global.text_data_en, "obj_encountertrigger1_3", "* You must be wondering&  what is going on.../")
ds_map_add(global.text_data_en, "obj_encountertrigger1_4", "\W* I am \BTORIEL\W, caretaker&  of the \RRUINS\W./")
ds_map_add(global.text_data_en, "obj_encountertrigger1_5", "* I pass through here&  every day to see if&  anyone has fallen down./")
ds_map_add(global.text_data_en, "obj_encountertrigger1_6", "* It does not happen&  often./")
ds_map_add(global.text_data_en, "obj_encountertrigger1_7", "* You are the first to&  come here in a long&  time./")
ds_map_add(global.text_data_en, "obj_encountertrigger1_8", "* Do not be afraid,^1 &  little one./")
ds_map_add(global.text_data_en, "obj_encountertrigger1_9", "* I will do my best to&  protect you here../")
ds_map_add(global.text_data_en, "obj_encountertrigger1_10", "* Come!^2 I shall guide you&  through your new home./%%")
//Toriel in room_ruins2 
ds_map_add(global.text_data_en, "obj_torieltrigger1_1", "\E0* The RUINS are full of&  puzzles./")
ds_map_add(global.text_data_en, "obj_torieltrigger1_2", "* Ancient fusions between&  diversions and doorkeys./")
ds_map_add(global.text_data_en, "obj_torieltrigger1_3", "* They must be solved in&  order to move from room&  to room./")
ds_map_add(global.text_data_en, "obj_torieltrigger1_4", "* Allow me to demonstrate./%%")
//After Toriel solves the button puzzle
ds_map_add(global.text_data_en, "obj_torieltrigger1_5", "\E0* We are free to proceed&  now./")
ds_map_add(global.text_data_en, "obj_torieltrigger1_6", "* Follow me,^1 my child.^2 &* There are more puzzles&  ahead./%%")
//Start of room_ruins3
ds_map_add(global.text_data_en, "obj_torieltrigger2_1", "\E0* In this room,^1 you will&  need to trigger several&  switches./")
ds_map_add(global.text_data_en, "obj_torieltrigger2_2", "* Do not worry,^1 I have &  labelled the ones that&  you need to flip./%")
//Interact with Toriel before pressing the first switch
ds_map_add(global.text_data_en, "obj_torinteractable1_1", "\E1* The first switch is over&  on the wall./%") //Reused the original UT Dialogue here since UTY doesn't have repeat dialogue variants, and the original line just being a combination of both UT variants.
//Repeat interaction with Toriel before pressing the first switch
ds_map_add(global.text_data_en, "obj_torinteractable1_2", "\E1* Do you need some help..^1?&* Press the switch on the&  wall./")
ds_map_add(global.text_data_en, "obj_torinteractable1_3", "\E0* Come on,^1 you can do it!/%")
//Dialogue after pulling the first switch
ds_map_add(global.text_data_en, "obj_torieltrigger2_3", "\E0* Splendid!^2 &* I am proud of you,^1 my&  child./%")
//Interact with Toriel before pressing the second switch
ds_map_add(global.text_data_en, "obj_torinteractable2_1", "\E0* Go on^1, I believe in you!/")
ds_map_add(global.text_data_en, "obj_torinteractable2_2", "* Only one more switch&  remains./%")
//Repeat interaction with Toriel before pressing the second switch
ds_map_add(global.text_data_en, "obj_torinteractable2_3", "\E0* The last switch is to&  your left./")
ds_map_add(global.text_data_en, "obj_torinteractable2_4", "\E1* You do know which way&  left is^1, do you not?/%")
//Interact with the rigged switch before pressing the second switch.
ds_map_add(global.text_data_en, "obj_readable_switch1_1", "\E1* Oh no,^1 my child!^2 &* That is the wrong&  switch./")
ds_map_add(global.text_data_en, "obj_readable_switch1_2", "\E0* I have labelled the one& you need to flip./%")
//After pulling second switch
ds_map_add(global.text_data_en, "obj_torieltrigger2_4", "\E1* ...It should have opened&  by now.../")
ds_map_add(global.text_data_en, "obj_torieltrigger2_5", "* I am sure I labelled the&  correct lever.../")
ds_map_add(global.text_data_en, "obj_torieltrigger2_6", "* Ah,^1 do not worry,^1 little&  one!^2 Try flipping the&  other switch./%")
//NOOOOO MY CHILD YOU FELL INTO THE UNDERTALE YELLOW!!!!
ds_map_add(global.text_data_en, "scr_text_plothole_1", "* My child!/")
ds_map_add(global.text_data_en, "scr_text_plothole_2", "* Are you all right?/")
ds_map_add(global.text_data_en, "scr_text_plothole_3", "* .../")
ds_map_add(global.text_data_en, "scr_text_plothole_4", "* Oh dear...^2 &* I am afraid I cannot reach&  you.../")
ds_map_add(global.text_data_en, "scr_text_plothole_5", "* I must leave for a moment.^2 &* You will stay there,^1 will you&  not?/")
ds_map_add(global.text_data_en, "scr_text_plothole_6", "* Do not wander,^1 many monsters&  are unfriendly towards humans./")
ds_map_add(global.text_data_en, "scr_text_plothole_7", "* Fret not,^1 my child,^1 I will&  protect you!/")
ds_map_add(global.text_data_en, "scr_text_plothole_8", "* Please...^2 wait there./%")

//DARK RUINS//

//Readable Signs//
ds_map_add(global.text_data_en, "obj_readable_room1_darkruins1_1", "* The sign is obscured by&  leaves./%%")

ds_map_add(global.text_data_en, "obj_readable_room1_darkruins4_1", "* (It's a sign.)^2 &* (It says\R EXPOSITION\W in large&  friendly letters.)/%%")

ds_map_add(global.text_data_en, "obj_readable_room1_darkruins6_1", "* Stuck? Press this for a&  do-over./")
ds_map_add(global.text_data_en, "obj_readable_room1_darkruins6_2", "* Or don't./%%")

//THEY JUST SAID THE SAME THING TWICE!
ds_map_add(global.text_data_en, "obj_readable_room2_darkruins6_1", "* Make what is dim, bright./")
ds_map_add(global.text_data_en, "obj_readable_room2_darkruins6_2", "* Make what is dark, light./%%")

ds_map_add(global.text_data_en, "obj_readable_room1_darkruins7_1", "* Private property. &* No trespassing./%%")

ds_map_add(global.text_data_en, "obj_readable_room1_darkruins9_1", "* Friend:^2 &* I planted these for you./")
ds_map_add(global.text_data_en, "obj_readable_room1_darkruins9_2", "* It isn't much but I hope it&  brightens your day./")
ds_map_add(global.text_data_en, "obj_readable_room1_darkruins9_3", "* It always brightened mine./%%")

//Cutscenes//

//Flowey shows up and destroys canon by existing. First playthrough.
ds_map_add(global.text_data_en, "scr_text_floweyintro_1", "\W* Howdy^2!&* I'm\Y FLOWEY\W.^2 &* \YFLOWEY\W the \YFLOWER\W!/")
ds_map_add(global.text_data_en, "scr_text_floweyintro_2", "\E9* Hmm...^2 &* You look confused!/")
ds_map_add(global.text_data_en, "scr_text_floweyintro_3", "\E0* Toriel ought to have&  taught you how things&  work around here!/")
ds_map_add(global.text_data_en, "scr_text_floweyintro_4", "\E8* She didn't?/")
ds_map_add(global.text_data_en, "scr_text_floweyintro_5", "\E0* I guess little old me&  will have to do./")
ds_map_add(global.text_data_en, "scr_text_floweyintro_6", "* Ready? Here we go!/%%")
//Flowey Intro Battle
ds_map_add(global.text_data_en, "scr_text_floweyintro_7", "See that heart^1? &That is your SOUL^1,&the very culmination&of your being!/")
ds_map_add(global.text_data_en, "scr_text_floweyintro_8", "Your LV represents&your LOVE...\E6^2 it's.../")
ds_map_add(global.text_data_en, "scr_text_floweyintro_9", "\E9Heh...^2 I'm sure you&won't have to worry&about that./")
ds_map_add(global.text_data_en, "scr_text_floweyintro_10", "\E0In the Underground,^1 &monsters may try&to attack you!/")
ds_map_add(global.text_data_en, "scr_text_floweyintro_11", "\E6If you see bullets&like these.../")
ds_map_add(global.text_data_en, "scr_text_floweyintro_12", "\E0You need to avoid&them at all costs!/%%")
ds_map_add(global.text_data_en, "scr_text_floweyintro_13", "Try dodging my&bullets now!^1 &Here they come!^2 %%%")
//Dodge Flowey's bullets
ds_map_add(global.text_data_en, "scr_text_floweyintro_14", "Nice job there,^1 &buddy!^2 In case you&do get hit,^1 I can&SAVE your progress!/")
ds_map_add(global.text_data_en, "scr_text_floweyintro_15", "That means if&something bad&happens,^1 I can make&it unhappen for you./%%")
//Get hit by Flowey's bullets
ds_map_add(global.text_data_en, "scr_text_floweyintro_16", "\E8Sorry about that./")
ds_map_add(global.text_data_en, "scr_text_floweyintro_17", "\E0Let's try again!/%%")
ds_map_add(global.text_data_en, "scr_text_floweyintro_18", "Here they come!^2 &Dodge them all!^2 %%%")
//Dodge Flowey's bullets after getting hit or get hit by all of them. Absence of second line is intentional for recycling purposes.
ds_map_add(global.text_data_en, "scr_text_floweyintro_19", "\E0Since you're so bad&at dodging bullets,&I can SAVE your&progress for you./")
//Get hit by Flowey's bullets again
ds_map_add(global.text_data_en, "scr_text_floweyintro_20", "\E8What are you doing?^2 &Dodge.^1 The.^1 Bullets./")
ds_map_add(global.text_data_en, "scr_text_floweyintro_21", "\E0Don't mess it up&this time./%%")
//Get hit by Flowey's bullets again
ds_map_add(global.text_data_en, "scr_text_floweyintro_22", "\E3You sicko!^2 &Are you doing this&on purpose?!/")
ds_map_add(global.text_data_en, "scr_text_floweyintro_23", "Fine!^2 I'll just stop&sending them then./%%")
//Flowey Intro Battle ends. Back to Overworld Dialogue.
ds_map_add(global.text_data_en, "scr_text_floweyintro_24", "\E0* You probably want to go&  home,^1 don'tcha?/")
ds_map_add(global.text_data_en, "scr_text_floweyintro_25", "\E0* Well you've got a long&  journey ahead!/")
ds_map_add(global.text_data_en, "scr_text_floweyintro_26", "* If you ever need to&  save,^1 come look for me!/")
ds_map_add(global.text_data_en, "scr_text_floweyintro_27", "* I'll leave these little&  things around for you./%%")
//Flowey sinks inside the ground for a while. Save Star is present, then he rises back up to yap some more.
ds_map_add(global.text_data_en, "scr_text_floweyintro_28", "* That way it's easy to&  find me!/")
ds_map_add(global.text_data_en, "scr_text_floweyintro_29", "* If you see one don't&  hesitate to call me!/")
ds_map_add(global.text_data_en, "scr_text_floweyintro_30", "\E0* And then I'll save&  for you.^2 Like I just&  saved for you now!/")
ds_map_add(global.text_data_en, "scr_text_floweyintro_31", "\E1* .../")
ds_map_add(global.text_data_en, "scr_text_floweyintro_32", "\E9* There's one more&  thing.../")
ds_map_add(global.text_data_en, "scr_text_floweyintro_33", "\E8\W* The king of all the&  monsters, \RASGORE\W.../")
ds_map_add(global.text_data_en, "scr_text_floweyintro_34", "* He's been killing&  humans./")
ds_map_add(global.text_data_en, "scr_text_floweyintro_35", "\E8* The only way out is&  killing him and...^2 &  well.../")
ds_map_add(global.text_data_en, "scr_text_floweyintro_36", "\E4* You're pretty small.../")
ds_map_add(global.text_data_en, "scr_text_floweyintro_37", "\E8* That doesn't matter too&  much though./")
ds_map_add(global.text_data_en, "scr_text_floweyintro_38", "\E0* What matters is you've&  got me on your side!/")
ds_map_add(global.text_data_en, "scr_text_floweyintro_39", "* I'll let you get going,^1 &  but please be careful./")
ds_map_add(global.text_data_en, "scr_text_floweyintro_40", "\E9* There's all sortsa&  dangerous traps down&  here./")
ds_map_add(global.text_data_en, "scr_text_floweyintro_41", "\E1* And some of the&  monsters in this&  place.../")
ds_map_add(global.text_data_en, "scr_text_floweyintro_42", "\E9* I hear they don't&  like visitors.^2 &* So good luck!/%%")

//Interact with room_darkruins03 Flowey Save Point after tutorial
//ds_map_add(global.text_data_en, "scr_text_floweysave1_1", "\E0* Howdy!^2 &* Looks like you got&  it then!/%%")
ds_map_add(global.text_data_en, "scr_text_floweysave1_1", "\E0* Howdy!^2 &* Looks like you got&  it then!/%%")
//Interact with room_darkruins03 Flowey Save Point again
ds_map_add(global.text_data_en, "scr_text_floweysave1_2", "\E0* Why the long face, pal?/")
ds_map_add(global.text_data_en, "scr_text_floweysave1_3", "\E0* Don't worry,^1 this place&  is way better than up&  there!/")
ds_map_add(global.text_data_en, "scr_text_floweysave1_4", "\E9* That old lady would've&  just spoiled all of&  our fun!/")
ds_map_add(global.text_data_en, "scr_text_floweysave1_5", "\E0* Come on,^1 let's not stand&  around here all day!/%%")
//Interact with room_darkruins03 Flowey Save Point a third time. First line of dialogue is different, so this sequence will need to be re-reviewed for Localization.
ds_map_add(global.text_data_en, "scr_text_floweysave1_6", "\E8* I've already saved for&  you.../")
ds_map_add(global.text_data_en, "scr_text_floweysave1_7", "\E9* Do you not trust me or&  something?/")
ds_map_add(global.text_data_en, "scr_text_floweysave1_8", "\E0* Come on!^2 &* I'm your pal!/")
ds_map_add(global.text_data_en, "scr_text_floweysave1_9", "\E0* I got your back!/%%")
//Repeat interactions with room_darkruins03 Flowey Save Point after the third time, but not on the sixth.
ds_map_add(global.text_data_en, "scr_text_floweysave1_10", "\E8* You should get going.../%%")
//Interact with room_darkruins03 Flowey Save Point a sixth time. Bro freaks out so bad I made new dialogue variants so it is not triggered accidentally.
ds_map_add(global.text_data_en, "scr_text_floweysave1_11", "\E4* Really?^2 &* What is this about?/")
ds_map_add(global.text_data_en, "scr_text_floweysave1_12", "* I told you already,^1 you&  don't need that stupid&  goat lady!/")
ds_map_add(global.text_data_en, "scr_text_floweysave1_13", "* She couldn't have&  protected you anyway!/")
ds_map_add(global.text_data_en, "scr_text_floweysave1_14", "\E0* You have me!^2 &* I'm way better!/")
ds_map_add(global.text_data_en, "scr_text_floweysave1_15", "\E0* I'm your pal Flowey!/")
ds_map_add(global.text_data_en, "scr_text_floweysave1_16", "\E0* I'm the only friend&  you'll ever need!/")
ds_map_add(global.text_data_en, "scr_text_floweysave1_17", "\E0* Can Toriel save for you?^1 &* NO!/")
ds_map_add(global.text_data_en, "scr_text_floweysave1_18", "\E9* So let's get out of&  here while we're&  still young!/%%")
//Interact with room_darkruin03 Flowey Save Point a sixth time before gaining gold, EXP or solving the first puzzle.
ds_map_add(global.text_data_en, "scr_text_floweysave1_19", "\E9* You're having an awful&  lot of fun with this.../")
ds_map_add(global.text_data_en, "scr_text_floweysave1_20", "\E9* Making me go up and down&  for nothing./")
ds_map_add(global.text_data_en, "scr_text_floweysave1_21", "\E8* I may be your friend...^2 &  But I've got limits too,^1  y'know?/")
ds_map_add(global.text_data_en, "scr_text_floweysave1_22", "\E2* Guess I gotta put my&  roots down./")
ds_map_add(global.text_data_en, "scr_text_floweysave1_23", "\E0* I'm not going to come&  out until you do&  something worth saving./")
ds_map_add(global.text_data_en, "scr_text_floweysave1_24", "\E0* No slacking off now!/%%")
//Return after solving the first puzzle
ds_map_add(global.text_data_en, "scr_text_floweysave1_25", "\E9* Well...^2 I guess solving&  that puzzle counts?/")
ds_map_add(global.text_data_en, "scr_text_floweysave1_26", "\E0* I'll give you an A for&  effort at least./")
ds_map_add(global.text_data_en, "scr_text_floweysave1_27", "\E2* Now an A+...^2 &* You gotta work a little&  harder for that./%%")
//Talk to Flowey a second time afterwards
ds_map_add(global.text_data_en, "scr_text_floweysave1_29", "\E8* This again?^2 Seems like&  you didn't learn from&  last time./")
ds_map_add(global.text_data_en, "scr_text_floweysave1_30", "\E2* That's fine by me!^1 \E0&* See you later!/%%")
//Flowey comes back up afterwards.
ds_map_add(global.text_data_en, "scr_text_floweysave1_31", "\E0* Just kidding!^2 &* You didn't think I'd do&  that again,^1 did you?/")
ds_map_add(global.text_data_en, "scr_text_floweysave1_32", "\E2* Not THIS time,^1 anyway./")
ds_map_add(global.text_data_en, "scr_text_floweysave1_33", "\E0* I've got nothing to say,^1  so poking at me won't do&  you any good!/%%")
//Flowey not giving new dialogue
ds_map_add(global.text_data_en, "scr_text_floweysave1_34", "\E0* Get going!/%%")

//Interact with room

//First Dalv Meeting
ds_map_add(global.text_data_en, "scr_text_dalvscene1_1", "* Hello.../")
ds_map_add(global.text_data_en, "scr_text_dalvscene1_2", "* I'm happy to finally meet you&  face to face./")
ds_map_add(global.text_data_en, "scr_text_dalvscene1_3", "* How long has it been?/")
ds_map_add(global.text_data_en, "scr_text_dalvscene1_4", "* I was wondering if you'd ever&  come back.../")
ds_map_add(global.text_data_en, "scr_text_dalvscene1_5", "* .../")
ds_map_add(global.text_data_en, "scr_text_dalvscene1_6", "* No...^2 too forward./")
ds_map_add(global.text_data_en, "scr_text_dalvscene1_7", "* Who am I kidding?^2 &* I'll never be able to meet you&  in this state./")
ds_map_add(global.text_data_en, "scr_text_dalvscene1_8", "* I just hope you know...^2 &* I had no choice.^1 &* It must be this way./%%")
//Dalv moves forward a bit before hitting us with another "...". Reusing the one he already he did.
ds_map_add(global.text_data_en, "scr_text_dalvscene1_9", "* Huh?/%%")
//Dalv turns around to see Clover from Undertale Yellow.
ds_map_add(global.text_data_en, "scr_text_dalvscene1_10", "* Who...?/")
ds_map_add(global.text_data_en, "scr_text_dalvscene1_11", "* I must be seeing things.../%%") //Removed Dalv's stutter here, since he does not seem to have this as a nervous tick like Alphys does.
//Dalv moves backwards and then moves into the next room, where the camera then returns to Clover.


ds_map_add(global.text_data_en, "scr_text_dalvscene2_1", "* I enjoyed life before...^2 &* I did... but I can't go back./")
ds_map_add(global.text_data_en, "scr_text_dalvscene2_2", "* What happened that day would&  only repeat./&&")
ds_map_add(global.text_data_en, "scr_text_dalvscene2_3", "* .../%%")
//Dalv turns around and sees Clover from Undertale Yellow again.
//Dalv does a exclamation mark in textbox originally, but that has been omitted for redundancy as the balloon icons already exist to fill that purpose.
ds_map_add(global.text_data_en, "scr_text_dalvscene2_4", "* What is this?/")
ds_map_add(global.text_data_en, "scr_text_dalvscene2_5", "* Why do they appear every time& I start monologuing?/")
ds_map_add(global.text_data_en, "scr_text_dalvscene2_6", "* I need more rest./%%")
//Dalv then walks away and we get back to Clover.

//We meet Dalv again near the entrance to his house.
ds_map_add(global.text_data_en, "scr_text_dalvscene3_1", "* You're...^2 still following me?/")
ds_map_add(global.text_data_en, "scr_text_dalvscene3_2", "* I thought I made it clear that&  I want to be left alone./%%")
//Pause for a bit, then Dalv turns to see Clover Undertale Yellow once more.
ds_map_add(global.text_data_en, "scr_text_dalvscene3_3", "* I don't understand...^2 &* You... you look just like them./")
ds_map_add(global.text_data_en, "scr_text_dalvscene3_4", "* Is this some sort of haunting?^2 &  Or have you come to finish the job?/")


//Dune your mom

//Talk to Gilbert in room_dunes_19
ds_map_add(global.text_data_en, "scr_text_gilbertNPC1_1", "\E0* Welcome to the Mining&  Co. Mines!^2 &* (Oh dear...^1 A visitor...)/") //The dialogue space here was hella cramped in the original. A little tricky to fit it all still.
ds_map_add(global.text_data_en, "scr_text_gilbertNPC1_2", "* If you have an inquiry,^1 &  please take it up with&  my assistant./%%")
//Slight pause, then Angie talks.
ds_map_add(global.text_data_en, "scr_text_gilbertNPC1_3", "\E2* Gilbert,^1 please.^2 &  We've been married for&  27 years./")
ds_map_add(global.text_data_en, "scr_text_gilbertNPC1_4", "\E0* You can handle the&  questions yourself./")
//Face switches to Gilbert.
ds_map_add(global.text_data_en, "scr_text_gilbertNPC1_5", "\E1* Um...^1 Certainly dear!/") //Gilbert doesn't seem to consistently have a stutter as a nervous tick like Alphys does, so this instance of that has been removed.
ds_map_add(global.text_data_en, "scr_text_gilbertNPC1_6", "\E0* Ahem.../")
ds_map_add(global.text_data_en, "scr_text_gilbertNPC1_7", "* If you're gonna ask&  about the hot&  conditions.../")
ds_map_add(global.text_data_en, "scr_text_gilbertNPC1_8", "* I'm ordering more&  Glacialstone Cold Packs&  later today./")
ds_map_add(global.text_data_en, "scr_text_gilbertNPC1_9", "* And if you're gonna ask&  about the falling rocks,/")
ds_map_add(global.text_data_en, "scr_text_gilbertNPC1_10", "* I'm gonna investigate&  it soon!/")
ds_map_add(global.text_data_en, "scr_text_gilbertNPC1_11", "* No need to worry,^1 &  everything is fine!/")
//ds_map_add(global.text_data_en, "scr_text_gilbertNPC1_12", "\E1* So...^2 what is it?/")
ds_map_add(global.text_data_en, "scr_text_gilbertNPC1_12", "* \E1* So...^2 what is it?& &         Firing      Elevator\C ")
//Select "Firing" Dialogue Option.
ds_map_add(global.text_data_en, "scr_text_gilbertNPC1a_1", "* Someone isn't doing&  their job correctly?/")
ds_map_add(global.text_data_en, "scr_text_gilbertNPC1a_2", "\E0* Well I never!/")
ds_map_add(global.text_data_en, "scr_text_gilbertNPC1a_3", "* They deserve a good&  slap on the wrist,^1 that  they do!/")
ds_map_add(global.text_data_en, "scr_text_gilbertNPC1a_4", "* One more mistake and I&  might put them in the&  timeout corner!/")
ds_map_add(global.text_data_en, "scr_text_gilbertNPC1a_5", "\E1* I'll uh...^2 send Angie&  down to confront them./")
ds_map_add(global.text_data_en, "scr_text_gilbertNPC1a_6", "\E0* You won't fire them&  will you?/")
ds_map_add(global.text_data_en, "scr_text_gilbertNPC1a_7", "\E1* Of course not!/")
ds_map_add(global.text_data_en, "scr_text_gilbertNPC1a_8", "\E0* The only monster I ever&  fired was the health&  inspector./")
ds_map_add(global.text_data_en, "scr_text_gilbertNPC1a_9", "* Fired him before he&  arrived./%%")
//Select "Elevator" Dialogue Option.
ds_map_add(global.text_data_en, "scr_text_gilbertNPC1b_1", "* The elevator was broken?^2 &  That can't be right./")
ds_map_add(global.text_data_en, "scr_text_gilbertNPC1b_2", "\E0* We refurbished it last&  month./")
ds_map_add(global.text_data_en, "scr_text_gilbertNPC1b_3", "* The company was given a&  repair budget for the&  whole mine./")
ds_map_add(global.text_data_en, "scr_text_gilbertNPC1b_4", "\E0* We refurbished it last&  month./")
ds_map_add(global.text_data_en, "scr_text_gilbertNPC1b_5", "* Turns out marble walls&  and gold tiling adds up&  quick./")
ds_map_add(global.text_data_en, "scr_text_gilbertNPC1b_6", "\E1* We ran out./")
ds_map_add(global.text_data_en, "scr_text_gilbertNPC1b_7", "\E2* Gorgeous baseboard job,^1 &  though.^2 &* Totally worth it./%%")
//Talk to Gilbert a second time.
ds_map_add(global.text_data_en, "scr_text_gilbertNPC2_1", "\E1* I take great pride in&  these mines./")
ds_map_add(global.text_data_en, "scr_text_gilbertNPC2_2", "\E0* Been supervising them&  for around thirty years!/")
ds_map_add(global.text_data_en, "scr_text_gilbertNPC2_3", "* Here every single day./")
ds_map_add(global.text_data_en, "scr_text_gilbertNPC2_4", "* I did take a week off&  when my kiddo was born./")
ds_map_add(global.text_data_en, "scr_text_gilbertNPC2_5", "\E1* But was right back at&  it when the time came./")
ds_map_add(global.text_data_en, "scr_text_gilbertNPC2_6", "* Strangely,^1 the progress&  report for that week&  was above average./%%")
//Talk to Gilbert a third time onwards.
ds_map_add(global.text_data_en, "scr_text_gilbertNPC3_1", "\E0* If you ever see my kid& out there.../")
ds_map_add(global.text_data_en, "scr_text_gilbertNPC3_2", "\E2* Tell 'em that their&  old man misses 'em!/")
//Talk to Gilbert during Genocide.
ds_map_add(global.text_data_en, "scr_text_gilbertNPC4_1", "\E0* I heard some rumblings&  of danger back west./")
ds_map_add(global.text_data_en, "scr_text_gilbertNPC4_2", "* Sent everyone home for&  now./")
ds_map_add(global.text_data_en, "scr_text_gilbertNPC4_3", "* Waiting to see if it&  was a false alarm or&  not./")
ds_map_add(global.text_data_en, "scr_text_gilbertNPC4_4", "* Sure hope everything's&  okay.../%%")
//Talk to Gilbert a second time during Genocide.
ds_map_add(global.text_data_en, "scr_text_gilbertNPC5_1", "\E0* Haven't had an&  emergency like this&  since the old cave in./")
ds_map_add(global.text_data_en, "scr_text_gilbertNPC5_2", "* Abandoned a good&  facility that day./%%")
//Talk to Gilbert a third time onwards during Genocide.
ds_map_add(global.text_data_en, "scr_text_gilbertNPC6_1", "\E0* If you're leaving,^1 stay  safe out there./")
ds_map_add(global.text_data_en, "scr_text_gilbertNPC6_2", "* But I wouldn't&  recommend roaming around&  right now./%%")

//Talk to Angie in room_dunes_19
ds_map_add(global.text_data_en, "scr_text_angieNPC1_1", "\E0* Hello there!/")
ds_map_add(global.text_data_en, "scr_text_angieNPC1_2", "* But I wouldn't&  recommend roaming around&  right now./%%")

//ds_map_add(global.text_data_en, "scr_text_gilbertNPC1b_8", "\E0* We refurbished it last&  month./")
